Repository ispp-2324-ocial/landing-page, pull requests merged in 2024-03, with the labels that each got.

#18 feat: add CF Pages deployment information to README.md
  README.md
Labels: blocked

#24 feat: política de privacidad y customer agreement
  src/components/footer.astro
  src/pages/customeragreement.astro
  src/pages/privacy.astro
Labels: enhancement, documentation

#25 fix(ci): workflow error
  .github/workflows/deploy.yml
Labels: hotfix
